spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

env.jwt_secret=${JWT_SECRET}

env.momo.endpoint=test
env.momo.partner_code=test
env.momo.access_key=test
env.momo.secret_key=test
env.momo.ipn=test
env.momo.return=test